<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Squirrel">
      <HintPath>..\..\src\Spotnet\lib\Squirrel.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
