using Spotnet.Helpers;
using Xunit;

namespace Spotnet.Tests
{
    /// <summary>
    /// Pins the cipher against text the .NET Framework build really produced.
    /// </summary>
    /// <remarks>
    /// The initialization vector in the source is eighteen bytes and AES uses sixteen.
    /// .NET Framework's RijndaelManaged silently took the first sixteen; .NET checks the
    /// length and throws, which is what stopped the migrated build at startup - this
    /// cipher protects the user's signing key, and it is read while the main window
    /// initializes.
    ///
    /// Truncating the vector is therefore not a detail: get it wrong in either direction
    /// and every existing key becomes unreadable. These ciphertexts were generated by the
    /// original code compiled against .NET Framework, so they fail if the vector, the key
    /// derivation, the mode or the padding ever drift.
    /// </remarks>
    public class StringCipherTests
    {
        [Theory]
        [InlineData("aBASE64KEYMATERIAL==", "eSC/jb8B8UhyF0WHTftGMP7LTRuP3MTb98IW4WCahKI=")]
        [InlineData("spotnet", "KmsihpKLsnmwThYbbSme2w==")]
        [InlineData("", "7YxU4MZcc5eWsTNb68XxuQ==")]
        public void TextEncryptedByTheDotNetFrameworkBuildStillDecrypts(string plainText, string cipherText)
        {
            Assert.Equal(plainText, StringCipher.Decrypt(cipherText));
        }

        [Theory]
        [InlineData("aBASE64KEYMATERIAL==", "eSC/jb8B8UhyF0WHTftGMP7LTRuP3MTb98IW4WCahKI=")]
        [InlineData("spotnet", "KmsihpKLsnmwThYbbSme2w==")]
        [InlineData("", "7YxU4MZcc5eWsTNb68XxuQ==")]
        public void EncryptionStillProducesWhatTheDotNetFrameworkBuildProduced(string plainText, string cipherText)
        {
            // Both directions, so a profile written by this build stays readable by the
            // previous one for as long as anyone might roll back.
            Assert.Equal(cipherText, StringCipher.Encrypt(plainText));
        }

        [Fact]
        public void ARoundTripSurvivesTextOutsideAscii()
        {
            const string value = "wachtwoord met accenten: éüñ — en een em-dash";

            Assert.Equal(value, StringCipher.Decrypt(StringCipher.Encrypt(value)));
        }
    }
}
