using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using Spotnet.Mac.PostProcessing;
using Xunit;

namespace Spotnet.Mac.Tests;

/// <summary>
/// Covers the built-in par2 implementation: field arithmetic, format parsing,
/// slice verification and Reed-Solomon repair.
///
/// The fixtures are generated by <see cref="Par2Fixture"/>, whose Reed-Solomon
/// encoder is written independently of the production code, so a repair only
/// passes here if both implementations agree on the same reading of the spec.
/// </summary>
public sealed class Par2Tests : IDisposable
{
    private readonly string _dir;

    public Par2Tests()
    {
        _dir = Path.Combine(Path.GetTempPath(), "spotnet-par2-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_dir);
    }

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); } catch { /* temp dir */ }
    }

    private static void Ignore(string _) { }
    private string Path_(string name) => Path.Combine(_dir, name);

    private static byte[] Payload(int length, int seed)
    {
        var data = new byte[length];
        new Random(seed).NextBytes(data);
        return data;
    }

    // ── field arithmetic ──────────────────────────────────────────────────────

    [Fact]
    public void The_field_is_closed_and_multiplication_has_inverses()
    {
        var rnd = new Random(99);
        for (int i = 0; i < 2000; i++)
        {
            ushort a = (ushort)rnd.Next(1, 65536);
            ushort b = (ushort)rnd.Next(1, 65536);

            ushort product = Galois16.Multiply(a, b);
            Assert.NotEqual(0, product);                                  // no zero divisors
            Assert.Equal(a, Galois16.Divide(product, b));                 // division undoes it
            Assert.Equal(1, Galois16.Multiply(a, Galois16.Reciprocal(a)));
            Assert.Equal(Galois16.Multiply(b, a), product);               // commutative
        }
    }

    [Fact]
    public void Multiplication_is_associative_and_distributes_over_xor()
    {
        var rnd = new Random(7);
        for (int i = 0; i < 500; i++)
        {
            ushort a = (ushort)rnd.Next(1, 65536);
            ushort b = (ushort)rnd.Next(1, 65536);
            ushort c = (ushort)rnd.Next(1, 65536);

            Assert.Equal(
                Galois16.Multiply(Galois16.Multiply(a, b), c),
                Galois16.Multiply(a, Galois16.Multiply(b, c)));

            Assert.Equal(
                Galois16.Multiply(a, (ushort)(b ^ c)),
                (ushort)(Galois16.Multiply(a, b) ^ Galois16.Multiply(a, c)));
        }
    }

    [Fact]
    public void Powers_agree_with_repeated_multiplication()
    {
        for (ushort a = 2; a < 40; a++)
        {
            ushort expected = 1;
            for (uint e = 0; e < 20; e++)
            {
                Assert.Equal(expected, Galois16.Pow(a, e));
                expected = Galois16.Multiply(expected, a);
            }
        }
    }

    [Fact]
    public void Base_constants_skip_the_exponents_par2_skips()
    {
        // 65535 = 3 · 5 · 17 · 257, so par2 keeps exponents 1, 2, 4, 7, 8, 11, …
        ushort[] bases = Galois16.BaseConstants(6);
        Assert.Equal(new ushort[]
        {
            Galois16.Pow(2, 1),
            Galois16.Pow(2, 2),
            Galois16.Pow(2, 4),
            Galois16.Pow(2, 7),
            Galois16.Pow(2, 8),
            Galois16.Pow(2, 11)
        }, bases);

        // Every base must be distinct, or the matrix could not be inverted.
        ushort[] many = Galois16.BaseConstants(2000);
        Assert.Equal(many.Length, many.Distinct().Count());
    }

    // ── parsing ───────────────────────────────────────────────────────────────

    [Fact]
    public void A_recovery_set_round_trips_through_the_parser()
    {
        byte[] a = Payload(9000, 1);
        byte[] b = Payload(2500, 2);
        File.WriteAllBytes(Path_("a.bin"), a);
        File.WriteAllBytes(Path_("b.bin"), b);

        Par2Fixture.Write(Path_("set.par2"), 4000,
            new[] { new Par2Fixture.InputFile("a.bin", a), new Par2Fixture.InputFile("b.bin", b) },
            recoveryBlocks: 3);

        Par2RecoverySet? set = Par2RecoverySet.Load(_dir, Ignore);

        Assert.NotNull(set);
        Assert.Equal(4000, set!.SliceSize);
        Assert.Equal(2, set.Files.Count);
        Assert.Equal(3, set.AvailableRecoveryBlocks);
        Assert.True(set.IsUsable);

        // 9000 bytes over 4000-byte slices is 3 slices; 2500 is 1.
        Assert.Equal(3, set.Files[0].SliceCount(set.SliceSize));
        Assert.Equal(1, set.Files[1].SliceCount(set.SliceSize));
        Assert.Equal(4, set.TotalSlices);
        Assert.Equal(0, set.Files[0].FirstSliceIndex);
        Assert.Equal(3, set.Files[1].FirstSliceIndex);

        // Per-slice checksums must be present for every slice.
        Assert.Equal(3, set.Files[0].SliceMd5.Count);
        Assert.Single(set.Files[1].SliceMd5);
    }

    // ── verification ──────────────────────────────────────────────────────────

    [Fact]
    public void An_intact_download_verifies_clean()
    {
        byte[] data = Payload(20_000, 3);
        File.WriteAllBytes(Path_("film.bin"), data);
        Par2Fixture.Write(Path_("film.par2"), 4000,
            new[] { new Par2Fixture.InputFile("film.bin", data) }, recoveryBlocks: 2);

        Par2VerifyResult result = Verify();

        Assert.True(result.AllFilesComplete);
        Assert.Equal(0, result.MissingSliceCount);
    }

    [Fact]
    public void A_single_flipped_byte_marks_exactly_one_slice_damaged()
    {
        byte[] data = Payload(20_000, 4);
        Par2Fixture.Write(Path_("film.par2"), 4000,
            new[] { new Par2Fixture.InputFile("film.bin", data) }, recoveryBlocks: 2);

        data[9000] ^= 0xFF;                     // lands in slice 2
        File.WriteAllBytes(Path_("film.bin"), data);

        Par2VerifyResult result = Verify();

        Assert.False(result.AllFilesComplete);
        Assert.Equal(new[] { 2 }, result.MissingSliceIndices);
    }

    [Fact]
    public void A_missing_file_counts_all_of_its_slices_as_missing()
    {
        byte[] a = Payload(12_000, 5);
        byte[] b = Payload(8_000, 6);
        File.WriteAllBytes(Path_("a.bin"), a);
        Par2Fixture.Write(Path_("set.par2"), 4000,
            new[] { new Par2Fixture.InputFile("a.bin", a), new Par2Fixture.InputFile("b.bin", b) },
            recoveryBlocks: 5);
        // b.bin is never written.

        Par2VerifyResult result = Verify();

        Assert.False(result.AllFilesComplete);
        Assert.Equal(new[] { 3, 4 }, result.MissingSliceIndices);
        Assert.Contains(result.Files, f => f.File.Name == "b.bin" && !f.Exists);
    }

    [Fact]
    public void A_truncated_file_is_caught_even_where_the_slices_still_hash()
    {
        byte[] data = Payload(16_000, 7);       // exactly 4 slices
        Par2Fixture.Write(Path_("film.par2"), 4000,
            new[] { new Par2Fixture.InputFile("film.bin", data) }, recoveryBlocks: 2);

        // Drop the last four bytes: par2 zero-pads, so the final slice would
        // otherwise be indistinguishable from a complete one.
        File.WriteAllBytes(Path_("film.bin"), data[..(data.Length - 4)]);

        Assert.False(Verify().AllFilesComplete);
    }

    // ── repair ────────────────────────────────────────────────────────────────

    [Fact]
    public void One_damaged_slice_is_repaired_and_verified()
    {
        byte[] data = Payload(20_000, 11);
        Par2Fixture.Write(Path_("film.par2"), 4000,
            new[] { new Par2Fixture.InputFile("film.bin", data) }, recoveryBlocks: 2);

        byte[] damaged = (byte[])data.Clone();
        for (int i = 4000; i < 8000; i++) damaged[i] ^= 0xA5;
        File.WriteAllBytes(Path_("film.bin"), damaged);

        Assert.Equal(Par2RepairOutcome.Repaired, Repair());

        Assert.Equal(Md5(data), Md5(File.ReadAllBytes(Path_("film.bin"))));
    }

    [Fact]
    public void Damage_spread_across_several_files_is_repaired()
    {
        byte[] a = Payload(12_000, 21);
        byte[] b = Payload(10_000, 22);
        byte[] c = Payload(4_000, 23);
        var files = new[]
        {
            new Par2Fixture.InputFile("a.bin", a),
            new Par2Fixture.InputFile("b.bin", b),
            new Par2Fixture.InputFile("c.bin", c)
        };
        Par2Fixture.Write(Path_("set.par2"), 4000, files, recoveryBlocks: 4);

        byte[] da = (byte[])a.Clone();
        for (int i = 0; i < 4000; i++) da[i] ^= 0x3C;              // a slice 0
        byte[] db = (byte[])b.Clone();
        for (int i = 8000; i < 10000; i++) db[i] ^= 0x77;          // b slice 2
        File.WriteAllBytes(Path_("a.bin"), da);
        File.WriteAllBytes(Path_("b.bin"), db);
        File.WriteAllBytes(Path_("c.bin"), c);

        Assert.Equal(Par2RepairOutcome.Repaired, Repair());

        Assert.Equal(Md5(a), Md5(File.ReadAllBytes(Path_("a.bin"))));
        Assert.Equal(Md5(b), Md5(File.ReadAllBytes(Path_("b.bin"))));
        Assert.Equal(Md5(c), Md5(File.ReadAllBytes(Path_("c.bin"))));
    }

    [Fact]
    public void A_file_that_is_gone_entirely_is_rebuilt()
    {
        byte[] a = Payload(12_000, 31);
        byte[] b = Payload(8_000, 32);
        var files = new[]
        {
            new Par2Fixture.InputFile("a.bin", a),
            new Par2Fixture.InputFile("b.bin", b)
        };
        Par2Fixture.Write(Path_("set.par2"), 4000, files, recoveryBlocks: 3);

        File.WriteAllBytes(Path_("a.bin"), a);
        // b.bin never arrives; both of its slices come out of the recovery data.

        Assert.Equal(Par2RepairOutcome.Repaired, Repair());

        Assert.True(File.Exists(Path_("b.bin")));
        Assert.Equal(Md5(b), Md5(File.ReadAllBytes(Path_("b.bin"))));
        Assert.Equal(b.Length, new FileInfo(Path_("b.bin")).Length);
    }

    [Fact]
    public void Repair_uses_exactly_as_many_recovery_blocks_as_it_needs()
    {
        byte[] data = Payload(40_000, 41);      // 10 slices
        Par2Fixture.Write(Path_("film.par2"), 4000,
            new[] { new Par2Fixture.InputFile("film.bin", data) }, recoveryBlocks: 4);

        byte[] damaged = (byte[])data.Clone();
        foreach (int slice in new[] { 1, 4, 7, 9 })
            for (int i = slice * 4000; i < Math.Min((slice + 1) * 4000, damaged.Length); i++)
                damaged[i] ^= 0x5A;
        File.WriteAllBytes(Path_("film.bin"), damaged);

        Assert.Equal(Par2RepairOutcome.Repaired, Repair());
        Assert.Equal(Md5(data), Md5(File.ReadAllBytes(Path_("film.bin"))));
    }

    [Fact]
    public void Repair_is_refused_when_the_damage_outruns_the_recovery_blocks()
    {
        byte[] data = Payload(20_000, 51);      // 5 slices
        Par2Fixture.Write(Path_("film.par2"), 4000,
            new[] { new Par2Fixture.InputFile("film.bin", data) }, recoveryBlocks: 1);

        byte[] damaged = (byte[])data.Clone();
        for (int i = 0; i < 12_000; i++) damaged[i] ^= 0x11;      // 3 slices gone, 1 block available
        File.WriteAllBytes(Path_("film.bin"), damaged);

        Par2VerifyResult verified = Verify();
        Assert.False(verified.CanRepair);
        Assert.Equal(2, verified.BlocksShort);
        Assert.Equal(Par2RepairOutcome.NotEnoughBlocks, Repair());

        // The damaged file is left exactly as it was; nothing half-written.
        Assert.Equal(Md5(damaged), Md5(File.ReadAllBytes(Path_("film.bin"))));
    }

    [Fact]
    public void A_clean_download_reports_that_no_repair_was_needed()
    {
        byte[] data = Payload(20_000, 61);
        File.WriteAllBytes(Path_("film.bin"), data);
        Par2Fixture.Write(Path_("film.par2"), 4000,
            new[] { new Par2Fixture.InputFile("film.bin", data) }, recoveryBlocks: 2);

        Assert.Equal(Par2RepairOutcome.NoRepairNeeded, Repair());
    }

    [Fact]
    public async System.Threading.Tasks.Task The_repair_stage_reports_its_verdict_to_the_caller()
    {
        byte[] data = Payload(20_000, 71);
        Par2Fixture.Write(Path_("film.par2"), 4000,
            new[] { new Par2Fixture.InputFile("film.bin", data) }, recoveryBlocks: 2);

        byte[] damaged = (byte[])data.Clone();
        for (int i = 4000; i < 8000; i++) damaged[i] ^= 0xA5;
        File.WriteAllBytes(Path_("film.bin"), damaged);

        var stage = new Par2Repair(_dir, Ignore);
        (bool ok, Par2Result result) = await stage.RunAsync();

        Assert.True(ok);
        Assert.Equal(Par2Result.Repaired, result);
        Assert.Equal(Md5(data), Md5(File.ReadAllBytes(Path_("film.bin"))));
    }

    [Fact]
    public async System.Threading.Tasks.Task The_repair_stage_asks_for_more_blocks_before_giving_up()
    {
        byte[] data = Payload(20_000, 81);
        Par2Fixture.Write(Path_("film.par2"), 4000,
            new[] { new Par2Fixture.InputFile("film.bin", data) }, recoveryBlocks: 1);

        byte[] damaged = (byte[])data.Clone();
        for (int i = 0; i < 12_000; i++) damaged[i] ^= 0x11;
        File.WriteAllBytes(Path_("film.bin"), damaged);

        int askedFor = -1;
        var stage = new Par2Repair(_dir, Ignore);
        (bool ok, Par2Result result) = await stage.RunAsync(
            tryFetchMoreBlocks: (short_, _) =>
            {
                askedFor = short_;
                // Simulate the extra par2 volume arriving from Usenet.
                Par2Fixture.Write(Path_("film.vol000+08.par2"), 4000,
                    new[] { new Par2Fixture.InputFile("film.bin", data) }, recoveryBlocks: 5);
                return System.Threading.Tasks.Task.FromResult(true);
            });

        Assert.Equal(2, askedFor);
        Assert.True(ok);
        Assert.Equal(Par2Result.Repaired, result);
        Assert.Equal(Md5(data), Md5(File.ReadAllBytes(Path_("film.bin"))));
    }

    [Fact]
    public void Par2_files_are_removed_without_touching_the_payload()
    {
        byte[] data = Payload(8_000, 91);
        File.WriteAllBytes(Path_("film.bin"), data);
        Par2Fixture.Write(Path_("film.par2"), 4000,
            new[] { new Par2Fixture.InputFile("film.bin", data) }, recoveryBlocks: 1);
        File.WriteAllBytes(Path_("film.vol000+01.PAR2"), new byte[10]);

        new Par2Repair(_dir, Ignore).RemovePar2Files();

        Assert.True(File.Exists(Path_("film.bin")));
        Assert.Empty(Directory.GetFiles(_dir).Where(p => ArchiveNaming.IsPar2File(Path.GetFileName(p))));
    }

    // ── helpers ───────────────────────────────────────────────────────────────

    private Par2VerifyResult Verify()
    {
        Par2RecoverySet set = Par2RecoverySet.Load(_dir, Ignore)!;
        return new Par2Verifier(_dir, set, Ignore).Verify();
    }

    private Par2RepairOutcome Repair()
    {
        Par2RecoverySet set = Par2RecoverySet.Load(_dir, Ignore)!;
        Par2VerifyResult verified = new Par2Verifier(_dir, set, Ignore).Verify();
        return new Par2Repairer(_dir, set, Ignore).Repair(verified);
    }

    private static string Md5(byte[] data) => Convert.ToHexString(MD5.HashData(data));
}
